export const members = [
  {
    role: 'Operational Admin',
    image: '/img/aboutus/team/amalia.jpg',
    name: 'Amalia Utami',
    twitter: '#',
    linkedin: '#',
    description: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor',
  },
  {
    role: 'Operational Admin',
    image: '/img/aboutus/team/aodia.jpg',
    name: 'Aodia Chandra',
    twitter: '#',
    linkedin: '#',
    description: 'Habitant morbi tristique senectus et netus et malesuada fames. Vestibulum morbi',
  },
  {
    role: 'Operational Admin',
    image: '/img/aboutus/team/nawar.jpg',
    name: 'Astri Nawwar',
    twitter: '#',
    linkedin: '#',
    description: 'Quis risus sed vulputate odio ut enim blandit volutpat. Amet cursus sit amet.',
  },
  {
    role: 'Operational Admin',
    image: '/img/aboutus/team/ivvana.jpg',
    name: 'Ivvana Sechan',
    twitter: '#',
    linkedin: '#',
    description: 'Quis risus sed vulputate odio ut enim blandit volutpat. Amet cursus sit amet.',
  },
  {
    role: 'Product Specialist',
    image: '/img/aboutus/team/astri.jpg',
    name: 'Astri Maulinda',
    twitter: '#',
    linkedin: '#',
    description:
      'Consectetur libero id faucibus nisl tincidunt eget nullam fringilla urna porttitor.',
  },
  {
    role: 'Finance',
    image: '/img/aboutus/team/athaya.jpg',
    name: 'Athaya Putri',
    twitter: '#',
    linkedin: '#',
    description:
      'Mi eget mauris pharetra et ultrices neque ornare aenean massa eget egestas purus.',
  },
  {
    role: 'Marketing Creative',
    image: '/img/aboutus/team/daffa.jpg',
    name: 'Brahmastya Daffa',
    twitter: '#',
    linkedin: '#',
    description: 'Diam maecenas sed enim ut sem viverra aliquet eget magna ac placerat vestibulum.',
  },
  {
    role: 'Production Manager',
    image: '/img/aboutus/team/ananta.jpg',
    name: 'Rizky Ananta',
    twitter: '#',
    linkedin: '#',
    description: 'Diam maecenas sed enim ut sem viverra aliquet eget magna ac placerat vestibulum.',
  },
  {
    role: 'Production Field',
    image: '/img/aboutus/team/mika.jpg',
    name: 'Mika Suryofakhri Rahwono',
    twitter: '#',
    linkedin: '#',
    description: 'Diam maecenas sed enim ut sem viverra aliquet eget magna ac placerat vestibulum.',
  },
  {
    role: 'Production Field',
    image: '/img/aboutus/team/fiqo.jpg',
    name: 'Fiqo Anugrah Rio',
    twitter: '#',
    linkedin: '#',
    description: 'Diam maecenas sed enim ut sem viverra aliquet eget magna ac placerat vestibulum.',
  },
  {
    role: 'Production Field',
    image: '/img/aboutus/team/gibran.jpg',
    name: 'Gibran Fuad',
    twitter: '#',
    linkedin: '#',
    description: 'Diam maecenas sed enim ut sem viverra aliquet eget magna ac placerat vestibulum.',
  },
  {
    role: 'Production Field',
    image: '/img/aboutus/team/monte.jpg',
    name: 'Montello',
    twitter: '#',
    linkedin: '#',
    description: 'Diam maecenas sed enim ut sem viverra aliquet eget magna ac placerat vestibulum.',
  },
  {
    role: 'Videographer & Photographer',
    image: '/img/aboutus/team/jidan.jpg',
    name: 'Jidan Auladi',
    twitter: '#',
    linkedin: '#',
    description: 'Diam maecenas sed enim ut sem viverra aliquet eget magna ac placerat vestibulum.',
  },
  {
    role: 'Product Specialist',
    image: '/img/aboutus/team/mirai.jpg',
    name: 'Mirai Annabila',
    twitter: '#',
    linkedin: '#',
    description: 'Diam maecenas sed enim ut sem viverra aliquet eget magna ac placerat vestibulum.',
  },
]
