export const slides = [
    {
      img: 'https://firebasestorage.googleapis.com/v0/b/website-ease.appspot.com/o/img%2Ficonservice%2Fveactorduduk%204.png?alt=media&token=2a25c5b4-eed0-40be-8c5d-0769e8a48c3b',
      heading: 'BEST LIVE STREAMING SERVICES',
      subheading1: 'With highly efficient features in event broadcasting, We help you digitalize your event with Our Live Streaming Services.',
      button: 'Book Now!',
      bground: 'https://firebasestorage.googleapis.com/v0/b/website-ease.appspot.com/o/img%2FBackground%201.png?alt=media&token=7b347cc5-f193-468f-81d1-f92e77e07d70',
      clor:'#000',
      link:'/services/creative',
      fontbase:'8vw',
      fontsm:'4vh',
      fontlg:'4.2vw',
    },
    {
      img: 'https://firebasestorage.googleapis.com/v0/b/website-ease.appspot.com/o/img%2Ficonservice%2Fzoomlogo3.png?alt=media&token=b58c7847-ecd6-439d-aac1-f8974b9569d5',
      heading: 'EASIEST WAY TO RENT ZOOM',
      subheading1: 'As a result of the pandemic, things that used to be held offline now shifted to online-based. Now, we are here to ease your needs. Zoom rental never been easier.',
      button: 'Book Now!',
      bground: 'https://firebasestorage.googleapis.com/v0/b/website-ease.appspot.com/o/img%2FBackground%202.png?alt=media&token=5f29dbc8-6459-404a-92dc-e2c30f45f70e',
      clor:'white',
      link:'/services/zoom',
      fontbase:'8vw',
      fontsm:'4vh',
      fontlg:'5vw',
    },
    {
      img: 'https://firebasestorage.googleapis.com/v0/b/website-ease.appspot.com/o/img%2Ficonservice%2Fstudiologo3.png?alt=media&token=8bb12c16-897d-4c1e-ad58-ffa2d48a3358',
      heading: 'PROFESSIONAL PHOTOGRAPHY & VIDEOGRAPHY SERVICES',
      subheading1: 'From 7 of 10 people, they prefer to choose brands that have high quality advertisements before deciding to purchase something. Improve your brand image with Ease Your Needs!',
      button: 'Book Now!',
      bground: 'https://firebasestorage.googleapis.com/v0/b/website-ease.appspot.com/o/img%2FBackground%203.png?alt=media&token=06ad7cc6-3e3e-4b0b-a36c-64f6f45306a4',
      clor:'white',
      link:'/services/studio',
      fontbase:'8vw',
      fontsm:'4vh',
      fontlg:'3.3vw',
    },
]